{
 "title": "Cisco trex",
 "description": "f",
 "tags": [ "generator" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "measurement", "query": "${VAR_MEASUREMENT}" },
   {
    "name": "hostname",
    "label": "Trex hostname",
    "query": "SHOW TAG VALUES FROM $measurement WITH KEY = \"host\""
   },
   {
    "name": "test_id",
    "label": "test",
    "query": "SHOW TAG VALUES FROM $measurement WITH KEY = \"test_id\" WHERE \"host\" =~ /^$hostname$/"
   },
   {
    "name": "nic_port",
    "label": "NIC port",
    "query": "SHOW TAG VALUES FROM \"trex_tests_latency\" WITH KEY = \"port\" WHERE \"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/"
   }
  ]
 },
 "panels": [
  {
   "title": "tmp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total connection drops",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "$A+$B+$C+$D", "type": "math" }
     ]
    },
    {
     "title": "Connection drops",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "($A+$F+$B+$C) / $D *100", "type": "math" }
     ]
    }
   ]
  },
  { "title": "Summary (L2)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Trex load profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_path" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Current TP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_rx_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Current PPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_rx_pps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_active_flows" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_tx_cps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_open_flows" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Total packets TX",
   "type": "stat",
   "description": "Total sent packets",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  {
   "title": "Profile multiplier",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_mult_float" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Load duration (HH:MM:SS)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "profile_client_m_traffic_duration"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Total bytes TX",
   "type": "stat",
   "description": "Total sent bytes",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  { "title": "Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total drops, bytes",
   "type": "stat",
   "description": "Relevant only for the whole test period",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Drops (by bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A+$B) / ($C+$D)*100", "type": "math" }
   ]
  },
  {
   "title": "Total connection drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B+$C+$D+$E+$F+$G+$H-$I+$J", "type": "math" }
   ]
  },
  {
   "title": "Connection drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "($A-$B+$C+$D+$E+$F+$G+$H-$I+$J) / $K *100",
     "type": "math"
    }
   ]
  },
  {
   "title": "Avg Trex CPU utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_cpu_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Max Trex TX Queue length, packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_queue_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total allowed attacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_attack_allowed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "!=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Total sent attacks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_attack_allowed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "!=", "value": "main_profile" }
     ]
    }
   ]
  },
  { "title": "Trex health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Trex CPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_cpu_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Trex packets queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "packets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_queue_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total allocation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_total_alloc_error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total throughput (bit/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_tx_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_rx_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "RX Drops",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_rx_drop_bps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Packets rate (pps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_tx_pps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_rx_pps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Concurrent connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_active_flows" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Connections/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "alias": "connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "global_tx_cps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Client <==> Server. Gbps/PPS/CPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Avg packet size, bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "client side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_m_avg_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "server side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_m_avg_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "TX bw ratio",
   "type": "timeseries",
   "description": "Ratio betwean tx_bw_l7_r and tx_bw_l7_total_r 100% means no retransmition TCP",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "client side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_m_tx_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "server side",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_m_tx_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Client ==> Server throughput (bit/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "TCP: Client TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_sndbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "TCP: Server RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_rcvbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Client TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_sndbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Server RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_rcvbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Server ==> Client throughput (bit/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "TCP: Server TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_sndbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "TCP: Client RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_rcvbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Server TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_sndbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Client RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_rcvbyte" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Client ==> Server packet rate (pps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "TCP: Client TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_sndtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "TCP: Server RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_rcvtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Client TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_sndpkt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Server RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_rcvpkt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Server ==> Client packet rate (pps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "TCP: Server TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_sndtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "TCP: Client RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_rcvtotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Server TX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_sndpkt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "UDP: Client RX",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_rcvpkt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Client TCP sessions state per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "established/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_connects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "closed/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_closed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_drops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "embryounic drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_conndrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "timeout drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "profile_client_tcps_timeoutdrop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "keepalive drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_keepdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "test drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_tcps_testdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "persist state drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "profile_client_tcps_persistdrop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Server TCP sessions state per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "established/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_connects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "closed/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_closed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_drops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "embryonic drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_conndrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "timeout drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "profile_server_tcps_timeoutdrop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "keepalive drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_keepdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "test drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_tcps_testdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "persist drops/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "profile_server_tcps_persistdrop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Client UDP sessions state per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "established/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_connects" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "closed/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_closed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "dropped/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_client_udps_keepdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  {
   "title": "Server UDP sessions state per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "accepted/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_accepts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "closed/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_closed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    },
    {
     "alias": "dropped/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "profile_server_udps_keepdrops" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "=", "value": "main_profile" }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "ICMP packet rate by NIC port",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "total_sent_$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "select": [
      [
       { "params": [ "latency_hist_cnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency by NIC port",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "max_port_$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "select": [
      [
       { "params": [ "latency_hist_max_usec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "min_port_$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "select": [
      [
       { "params": [ "latency_hist_min_usec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "avg_from_start_port_$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "select": [
      [
       { "params": [ "latency_hist_s_avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    },
    {
     "alias": "max_from_start_port_$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "select": [
      [
       { "params": [ "latency_hist_s_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" }
     ]
    }
   ]
  },
  {
   "title": "NIC port_$nic_port histogram latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 98 },
   "repeat": "nic_port",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_latency_usec]]_usec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "latency_usec" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "query": "SELECT mean(\"latency_stats_m_jitter\") FROM \"trex_tests_latency\" WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "pckt_prcnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$nic_port$/" }
     ]
    }
   ]
  },
  {
   "title": "NIC port_$nic_port counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 130 },
   "repeat": "nic_port",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "trex_tests_latency",
     "query": "SELECT mean(/latency_stats_(.*)/) FROM \"trex_tests_latency\" WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"port\" =~ /^$nic_port$/) AND $timeFilter GROUP BY time($__interval), \"port\" fill(none)",
     "select": [
      [
       { "params": [ "latency_stats_m_jitter" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "port", "operator": "=~", "value": "/^$nic_port$/" }
     ]
    }
   ]
  },
  {
   "title": "Client <==> Server. Errors and TCP stack counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 }
  },
  {
   "title": "Errors Client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_c_nf_throttled\") AS \"err_c_nf_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_c_tuple_err\") AS \"err_c_tuple_err\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_cwf\") AS \"err_cwf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_dct\") AS \"err_dct\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_defer_no_template\") AS \"err_defer_no_template\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_flow_overflow\") AS \"err_flow_overflow\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_fragments_ipv4_drop\") AS \"err_fragments_ipv4_drop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_l3_cs\") AS \"err_l3_cs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_l4_cs\") AS \"err_l4_cs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_len_err\") AS \"err_len_err\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_no_memory\") AS \"err_no_memory\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_no_syn\") AS \"err_no_syn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_no_tcp_udp\") AS \"err_no_tcp_udp\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_no_template\") AS \"err_no_template\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_redirect_rx\") AS \"err_redirect_rx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_rx_throttled\") AS \"err_rx_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_err_s_nf_throttled\") AS \"err_s_nf_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_flows_other\") AS \"flows_other\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_ignored_ips\") AS \"ignored_ips\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_ignored_macs\") AS \"ignored_macs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_rss_redirect_drops\") AS \"rss_redirect_drops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_rss_redirect_queue_full\") AS \"rss_redirect_queue_full\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_rss_redirect_rx\") AS \"rss_redirect_rx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_rss_redirect_tx\") AS \"rss_redirect_tx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Errors Server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_c_nf_throttled\") AS \"err_c_nf_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_c_tuple_err\") AS \"err_c_tuple_err\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_cwf\") AS \"err_cwf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_dct\") AS \"err_dct\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_defer_no_template\") AS \"err_defer_no_template\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_flow_overflow\") AS \"err_flow_overflow\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_fragments_ipv4_drop\") AS \"err_fragments_ipv4_drop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_l3_cs\") AS \"err_l3_cs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_l4_cs\") AS \"err_l4_cs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_len_err\") AS \"err_len_err\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_no_memory\") AS \"err_no_memory\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_no_syn\") AS \"err_no_syn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_no_tcp_udp\") AS \"err_no_tcp_udp\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_no_template\") AS \"err_no_template\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_redirect_rx\") AS \"err_redirect_rx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_rx_throttled\") AS \"err_rx_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_err_s_nf_throttled\") AS \"err_s_nf_throttled\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_flows_other\") AS \"flows_other\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_ignored_ips\") AS \"ignored_ips\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_ignored_macs\") AS \"ignored_macs\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_rss_redirect_drops\") AS \"rss_redirect_drops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_rss_redirect_queue_full\") AS \"rss_redirect_queue_full\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_rss_redirect_rx\") AS \"rss_redirect_rx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_rss_redirect_tx\") AS \"rss_redirect_tx\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "TCP/UDP stack client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_badsyn\") AS \"tcps_badsyn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_conndrops\") AS \"tcps_conndrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_delack\") AS \"tcps_delack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_keepdrops\") AS \"tcps_keepdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_keeptimeo\") AS \"tcps_keeptimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_nombuf\") AS \"tcps_nombuf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_pawsdrop\") AS \"tcps_pawsdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_persistdrop\") AS \"tcps_persistdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_persisttimeo\") AS \"tcps_persisttimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvdupack\") AS \"tcps_rcvdupack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvafterclose\") AS \"tcps_rcvafterclose\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvbadoff\") AS \"tcps_rcvbadoff\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvbadsum\") AS \"tcps_rcvbadsum\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvpackafterwin\") AS \"tcps_rcvpackafterwin\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvduppack\") AS \"tcps_rcvduppack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvoffloads\") AS \"tcps_rcvoffloads\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvoopack\") AS \"tcps_rcvoopack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvoopackdrop\") AS \"tcps_rcvoopackdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvshort\") AS \"tcps_rcvshort\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rcvwinupd\") AS \"tcps_rcvwinupd\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rexmttimeo\") AS \"tcps_rexmttimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_rexmttimeo_syn\") AS \"tcps_rexmttimeo_syn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_sndrexmitpack\") AS \"tcps_sndrexmitpack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_sndurg\") AS \"tcps_sndurg\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_sndwinup\") AS \"tcps_sndwinup\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_testdrops\") AS \"tcps_testdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_timeoutdrop\") AS \"tcps_timeoutdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_udps_nombuf\") AS \"udps_nombuf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_udps_pkt_toobig\") AS \"udps_pkt_toobig\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_tcps_drops\") AS \"tcps_drops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_client_udps_keepdrops\") AS \"udps_keepdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "TCP/UDP stack server",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 173 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_badsyn\") AS \"tcps_badsyn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_conndrops\") AS \"tcps_conndrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_delack\") AS \"tcps_delack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_keepdrops\") AS \"tcps_keepdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_keeptimeo\") AS \"tcps_keeptimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_nombuf\") AS \"tcps_nombuf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_pawsdrop\") AS \"tcps_pawsdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_persistdrop\") AS \"tcps_persistdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_persisttimeo\") AS \"tcps_persisttimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvdupack\") AS \"tcps_rcvdupack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvafterclose\") AS \"tcps_rcvafterclose\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvbadoff\") AS \"tcps_rcvbadoff\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvbadsum\") AS \"tcps_rcvbadsum\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvpackafterwin\") AS \"tcps_rcvpackafterwin\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvduppack\") AS \"tcps_rcvduppack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvoffloads\") AS \"tcps_rcvoffloads\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvoopack\") AS \"tcps_rcvoopack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvoopackdrop\") AS \"tcps_rcvoopackdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvshort\") AS \"tcps_rcvshort\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rcvwinupd\") AS \"tcps_rcvwinupd\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rexmttimeo\") AS \"tcps_rexmttimeo\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_rexmttimeo_syn\") AS \"tcps_rexmttimeo_syn\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_sndrexmitpack\") AS \"tcps_sndrexmitpack\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_sndurg\") AS \"tcps_sndurg\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_sndwinup\") AS \"tcps_sndwinup\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_testdrops\") AS \"tcps_testdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_timeoutdrop\") AS \"tcps_timeoutdrop\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_udps_nombuf\") AS \"udps_nombuf\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_udps_pkt_toobig\") AS \"udps_pkt_toobig\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_tcps_drops\") AS \"tcps_drops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "$col",
     "query": "SELECT mean(\"profile_server_udps_keepdrops\") AS \"udps_keepdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" = 'main_profile') AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  { "title": "Attacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "Attacks status",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "query": "SELECT \"profile_name\", \"profile_path\", \"profile_client_udps_keepdrops\" FROM /^$measurement$/ WHERE (\"host\" =~ /^$hostname$/ AND \"test_id\" =~ /^$test_id$/ AND \"profile\" != 'main_profile') AND $timeFilter",
     "select": [
      [
       { "params": [ "profile_name" ], "type": "field" }
      ],
      [
       { "params": [ "profile_path" ], "type": "field" }
      ],
      [
       { "params": [ "global_attack_allowed" ], "type": "field" },
       { "params": [ "State" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "test_id", "operator": "=~", "value": "/^$test_id$/" },
      { "condition": "AND", "key": "profile", "operator": "!=", "value": "main_profile" }
     ]
    }
   ]
  }
 ]
}